server:
  # 服务端口
  port: 8899
  servlet:
    context-path: /robot
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

spring:
  datasource:
    url: jdbc:sqlite:D:/robot/db.sqlite
    driver-class-name: org.sqlite.JDBC
  # 配置 SpringBoot Admin Server 的地址
  # 用于将自身状态监控信息发送给 SpringBoot Admin Server
  boot:
    admin:
      client:
        url: http://localhost:9090
    # 应用程序名称（多个 SpringBoot 程序，可以配置相同的应用程序名称）
    application:
      name: robot

vlw:
  #vlm token
  token: bienaoccc
  #vlm 地址
  url: http://101.34.47.200:10006/

logging:
  config: classpath:logback-win.xml

# 收集当前 SpringBoot 的所有健康检查信息
management:
  endpoint:
    health:
      show-details: always
  # 将当前 SpringBoot 的所有监控端点暴露出来
  endpoints:
    web:
      exposure:
        include: "*"