server:
  # 服务端口
  port: 80
  servlet:
    context-path: /robot/api
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

spring:
  datasource:
    url: jdbc:sqlite:D:/robot/db.sqlite
    driver-class-name: org.sqlite.JDBC

vlw:
  #vlm token
  token: bienaoccc
  #vlm 地址
  url: http://101.34.47.200:10006/

logging:
  config: classpath:logback-win.xml