server:
  # 服务端口
  port: 8899
  servlet:
    context-path: /robot
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

spring:
  datasource:
    url: jdbc:sqlite:/usr/local/robot/db.sqlite
    driver-class-name: org.sqlite.JDBC

vlw:
  #vlm token
  token:
  #vlm 地址
  url:

logging:
  config: classpath:logback-linux.xml