spring:
  profiles:
    active: win
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
      continue-on-error: true
      data-locations: classpath:db/data.sql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bienao.robot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

JD_API_HOST: https://api.m.jd.com/client.action

task-function:
  shareHelp: true
  resetCkStatus: true
  checkCk: true
  updateShareCode: true
  countJd: true
