spring:
  profiles:
    active: win
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
      continue-on-error: true
      data-locations: classpath:db/data.sql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bienao.robot.entity
  configuration:
     # 打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

JD_API_HOST: https://api.m.jd.com/client.action

AUTH_ADDR: http://101.34.47.200:10027

VERSION: 1.0.7

task-function:
  shareHelp: true
  resetCkStatus: true
  checkCk: true
  updateShareCode: true
  countJd: true

# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 4
      # 配置最大线程数
      max_pool_size: 10
      # 配置队列大小
      queue_capacity: 10000
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-
